services:
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    volumes:
      - ./users-service:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://app:secret@database:5432/app?serverVersion=15&charset=utf8
      - TEST_DATABASE_URL=postgresql://app:secret@database:5432/app_test?serverVersion=15&charset=utf8
    command: ["/var/www/html/docker-entrypoint.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  notifications-service:
    build:
      context: ./notifications-service
      dockerfile: Dockerfile
    volumes:
      - ./notifications-service:/var/www/html
    depends_on:
      - rabbitmq
    ports:
      - "8082:8002"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: app
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 

volumes:
  database_data: